AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API and uses Lambda to processing Messages from SQS.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdaDocGenerator::lambdaDocGenerator.Function::FunctionHandler
      Runtime: dotnetcore3.1
      CodeUri: src/lambdaDocGenerator/bin/Release/netcoreapp3.1/lambdaDocGenerator.zip
      Description: Call the AWS Lambda API
      MemorySize: 256
      Timeout: 9
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active

  SQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdaDocGenerator::lambdaDocGenerator.SQSLambdaFunction::HandleSQSEvent
      Runtime: dotnetcore3.1
      CodeUri: src/lambdaDocGenerator/bin/Release/netcoreapp3.1/lambdaDocGenerator.zip
      Description: Process the message from a SQS queue
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties : {
      "ContentBasedDeduplication" : false,
      "DeduplicationScope" : queue,
      "DelaySeconds" : 0,
      "FifoQueue" : true,
      "FifoThroughputLimit" : perQueue,
      "MaximumMessageSize" : 262144,
      "MessageRetentionPeriod" : 345600,
      "QueueName" : opensearch2.fifo,
      "ReceiveMessageWaitTimeSeconds" : 0,
      "RedrivePolicy" : { "deadLetterTargetArn" : arn:aws:sqs:us-east-1:778996585753:opensearch-mydlq.fifo, "maxReceiveCount" : 100 },
      "VisibilityTimeout" :30
    }

